### ISSUE TITLE
Can you share me the source code of "train_optuna.py" and the hyper-parameter settings, as well as the corresponding environments?

### ISSUE THREAD

**Issue by MrYaoH** [MinhZou/UniG-Encoder#1]
Dear authors:

I hope everything's going well on your side! Recently, I have read your interesting work, and run the code with respect to "train_base.py". I indeed interest on your work, and expect to cite and follow your work.  However, I observe that the results are not comparable against the reported results in your paper. Then, I notice that README lead us to run "train_optuna.py", while the hub does not include this source code. This code seems to be related to hyper-parameters selection  (in the appendix, you claim that the hyper-parameters are selected by Optuna), which may indeed makes a significant impact on the results. Therefore, I wonder whether you can share me the code of "train_optuna.py" and the hyper-parameter settings?  Moreover, the corresponding environments, including the version of python, pytorch, pyg, etc., are also crucial for the results. Therefore, I also wonder if  you can report the configure of corresponding environments. I will appreciate your kindness if you can share these for me.

Thank you

**Comment by MinhZou** [comment]
Thank you for reaching out and for your interest in our work. We have recently uploaded the "train_optuna.py" file to the repository. The range of hyper-parameter settings can be found in the paper, particularly in the appendix.

However, I must apologize, as the specific hyper-parameter settings and environment configurations used in our experiments have been lost due to a server change. While this might affect the comparability of your results with those reported in the paper, slight variations are expected and acceptable within the scope of our findings.

Please feel free to reach out if you have any further questions or need additional assistance.
